# WFC Quality Targets (generated by wfc-init)
.PHONY: quality-check format lint test dev setup-dev dogfood preflight

quality-check: format lint
	@echo "All quality checks passed"

format:
	@echo "Formatting code..."
	@uv run black src/ tests/
	@echo "Code formatted"

lint:
	@echo "Linting..."
	@uv run ruff check src/ tests/
	@echo "Linting complete"

test:
	@uv run pytest tests/ -v

dev:
	@uv sync --group dev

setup-dev: dev
	@bash scripts/setup-dev.sh

dogfood:
	bash scripts/dogfood.sh

preflight: quality-check test dogfood
	@echo "Preflight complete."
